name: Production Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      run: |
        docker build -t your-username/simple-nodejs-app:latest .
        docker push your-username/simple-nodejs-app:latest

    - name: Deploy to Production Server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa user@${{ secrets.LOCAL_PROD_SERVER_IP }} 'docker pull your-username/simple-nodejs-app:latest && docker-compose -f /path/to/docker-compose.prod.yml up -d'
